apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-scripts
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  pull-repo.sh: |
{{ .Files.Get "scripts/pull-repo.sh" | indent 4 }}
  copy-secrets.sh: |
{{ .Files.Get "scripts/copy-secrets.sh" | indent 4 }}