{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "home-assistant.fullname" . }}-secrets"
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  secrets.yaml: |
    {{- .Values.secrets | b64enc | nindent 4 }}
{{ end }}